name: Build APK Real

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v4

    - name: Desempaquetar proyecto
      run: unzip -o showstation.zip -d . || true

    - name: Compilar APK con Buildozer Action
      uses: ArtemGovorov/buildozer-action@v1
      with:
        command: buildozer android debug
        repository_root: .

    - name: Guardar Archivo Final (APK)
      uses: actions/upload-artifact@v4
      with:
        name: Showstation-APK-Final
        path: bin/*.apk
